export const myData = {

    name: "Albrecht Barton",
    description: "🧑🏽‍🦱💻 I'm passionate Frontend Developer in love with React. Currently looking for first job opportunities.",
    email: "albrecht.barton@gmail.com",
    github: "https://github.com/Albrecht-Albi",
    linked: "https://pl.linkedin.com/in/albrecht-barton-41b922102",

    currentSkills: [
        "Semantic & accessible HTML",
        "Responsive Web Design",
        "Teamwork",
        "Markdown",
        "Immutability",
        "CSS BEM convention",
        "JavaScript ES6+",
        "CSS Grid",
        "CSS Flexbox",
        "Git",
        "React",
        "React Hooks",
        "React Router",
        "Redux (Toolkit)",
        "Redux-Saga",
        "Error handling",
        "Working with API (fetch, axios)",
        "Promises, Async/Await",
        "GitHub Pull Requests & Review",
        "Trello",
        "Scrum",
        "NPM",
    ],

    skillsToLearn: [
        "TypeScript",
        "Node.js",
        "React Context",
        "Cypress",
        "Unit testing",
        "JS classes",
        "React Native",
    ],
}